default: &default
  adapter: postgresql 
  encoding: unicode

development:
  <<: *default
  host: localhost
  database: mysitedevelopment
test:
  <<: *default
  host: localhost
  database: mysitetest

production:
  <<: *default
  database: mysiteproduction



